# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 13:59
from __future__ import unicode_literals

import canna_cross.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=canna_cross.models.company_upload)),
                ('link', models.URLField(blank=True, null=True)),
                ('continent', models.CharField(choices=[('af', 'Africa'), ('as', 'Asia'), ('eu', 'Europe'), ('na', 'North America'), ('sa', 'South America'), ('an', 'Antarctica'), ('au', 'Australia/Oceania')], max_length=10)),
                ('paper', models.BooleanField()),
                ('oil', models.BooleanField()),
                ('fuel', models.BooleanField()),
                ('clothing', models.BooleanField()),
                ('medicine', models.BooleanField()),
                ('science', models.BooleanField()),
                ('food', models.BooleanField()),
                ('buildings', models.BooleanField()),
            ],
        ),
    ]
