# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-08 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canna_cross', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='buildings',
            new_name='info_magazine',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='food',
            new_name='shops',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='fuel',
            new_name='homes_build_fuel',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='medicine',
            new_name='medicine_food',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='oil',
            new_name='cbd_oil',
        ),
    ]
