# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-08 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canna_cross', '0002_auto_20190809_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='homes_build_fuel',
            new_name='homes',
        ),
    ]
