# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-07 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seed',
            new_name='Strain',
        ),
        migrations.DeleteModel(
            name='SeedBank',
        ),
    ]
