# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_auto_20180807_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='strain',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.SeedBank'),
        ),
    ]
