# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_auto_20180820_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StrainPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='seedbank',
            name='link',
            field=models.URLField(),
        ),
    ]
