# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_auto_20180821_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='webId',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strainphoto',
            name='strain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.Strain'),
        ),
    ]
