# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 19:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0006_auto_20180827_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='relaxed',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
