# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0007_strain_relaxed'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='anxious',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='depression',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='dizzy',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='dry_eyes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dry Eyes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='dry_mouth',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dry Mouth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='energic',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='euphoric',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='fatigue',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='happy',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='lack_of_appetite',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Lack of Appetite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='pain',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='paranoid',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='stress',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='uplifted',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strain',
            name='relaxed',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
