# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0008_auto_20180827_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strain',
            old_name='anxious',
            new_name='anorexia',
        ),
        migrations.RenameField(
            model_name='strain',
            old_name='dizzy',
            new_name='choding_feeling',
        ),
        migrations.RenameField(
            model_name='strain',
            old_name='energic',
            new_name='communication',
        ),
        migrations.RenameField(
            model_name='strain',
            old_name='euphoric',
            new_name='creativ',
        ),
        migrations.RenameField(
            model_name='strain',
            old_name='fatigue',
            new_name='headache',
        ),
        migrations.RenameField(
            model_name='strain',
            old_name='happy',
            new_name='indica',
        ),
        migrations.RenameField(
            model_name='strain',
            old_name='paranoid',
            new_name='insomnia',
        ),
        migrations.RenameField(
            model_name='strain',
            old_name='uplifted',
            new_name='medicinal_mixtures',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='lack_of_appetite',
        ),
        migrations.AddField(
            model_name='strain',
            name='paranoia',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='pozitiv_emotion',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='relax',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='sativa',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strain',
            name='dry_eyes',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='strain',
            name='dry_mouth',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
