# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0009_auto_20180911_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='relaxed',
        ),
    ]
