# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0011_auto_20180914_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='info',
            field=models.TextField(blank=True, verbose_name='informace'),
        ),
    ]
