# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0013_auto_20180918_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='webId',
            field=models.SlugField(),
        ),
    ]
