# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import encyclopedia.models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0015_auto_20181003_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1900', 'before 1900'), ('2000', '1900 - 2000'), ('now', '2000 - now')], max_length=10)),
                ('header', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=encyclopedia.models.history_upload_to)),
            ],
        ),
    ]
