# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0016_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='standing',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
