# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import encyclopedia.models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0017_history_standing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revard',
            name='position',
        ),
        migrations.AddField(
            model_name='revard',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=encyclopedia.models.revard_upload),
        ),
        migrations.AddField(
            model_name='strain',
            name='revard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.Revard'),
        ),
    ]
