# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0018_auto_20181021_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedbank',
            name='link',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
