# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0019_auto_20181021_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='anorexia',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='choding_feeling',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='creativ',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='depression',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='dry_eyes',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='dry_mouth',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='headache',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='indica',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='insomnia',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='medicinal_mixtures',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='pain',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='paranoia',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='pozitiv_emotion',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='relax',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='sativa',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='stress',
        ),
    ]
