# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0021_auto_20181021_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strain',
            old_name='panaroid',
            new_name='paranoid',
        ),
    ]
