# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import encyclopedia.models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0023_auto_20181023_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupphoto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=encyclopedia.models.cup_upload),
        ),
    ]
