# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0024_auto_20181023_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedbank',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=300, null=True),
        ),
    ]
