# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0026_history_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedbank',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
