# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0028_strain_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='cup',
        ),
        migrations.AddField(
            model_name='strain',
            name='cup',
            field=models.ManyToManyField(blank=True, to='encyclopedia.Cup'),
        ),
    ]
