# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0029_auto_20181105_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupphoto',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
