# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0030_cupphoto_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupphoto',
            old_name='place',
            new_name='for_place',
        ),
        migrations.AddField(
            model_name='cup',
            name='info',
            field=models.TextField(blank=True, verbose_name='informace'),
        ),
        migrations.AddField(
            model_name='strain',
            name='cup_place',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
