# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import encyclopedia.models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0032_auto_20181121_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=encyclopedia.models.person_upload_to)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=encyclopedia.models.history_upload_to)),
                ('standing', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
