# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-08 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0035_history_short_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='short_info',
        ),
    ]
