# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-28 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='I read and agree'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'payed'), (3, 'sended')], default=1),
        ),
    ]
