# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-02 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'confirmed'), (4, 'payed'), (5, 'sended')], default=1),
        ),
    ]
