# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-09 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190303_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agree',
            field=models.BooleanField(verbose_name='I read and agree'),
        ),
    ]
